name = 0;
nameText = [ 
	["NAME: GUNN","BENCH PRESS: 200LBS","FAVORITE FOOD: SUSHI","HOBBY: CHESS BOXING"], 
	["NAME: LANG","BENCH PRESS: 405LBS","FAVORITE FOOD: BBQ PULLED PORK","HOBBY: BODYBUILDING"],
	["NAME: DRAGO","BENCH PRESS: 185LBS","FAVORITE FOOD: DEVILED EGGS","HOBBY: OIL PAINTING VIDEOS"],
	["NAME: CREED","BENCH PRESS: 315LBS","FAVORITE FOOD: RIBEYE","HOBBY: MOVIE BUFF"],
	["NAME: JAMES SHREDDER","BENCH PRESS: 225LBS","FAVORITE FOOD: STUFFED SHELLS","HOBBY: CIGAR SMOKING"],
]

myY = room_height/2;

image_index = 0;

drawPlayer = -110;
drawText = 0;

right = 1
left = -1;
dontMove = 0;
go = right;

pIndex = sprBoss1Run;